name: Validate TableView

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: cache-gradle-

      - name: Build
        run: ./gradlew :tableview:assembleDebug --no-daemon

  validate-sample:
    name: Validate sample app
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: cache-gradle-

      - name: Build
        run: ./gradlew :app:assembleDebug --no-daemon

  android-tests:
    name: Android Tests
    needs: build
    # Using macos-latest to take advantage of the hardware acceleration
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 15, 29 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: cache-gradle-

      - name: Android Test - API ${{ matrix.api-level }}
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: ./gradlew :tableview:connectedDebugAndroidTest --no-daemon
